server:
  port: 9201

service-url:
  user-service: http://localhost:8201


spring:
  cloud:
    gateway:
      routes:
          # 路由的ID
        - id: path_route
          # 匹配后路由地址
          uri: ${service-url.user-service}/user/{id}
          predicates:
              # 断言，路径相匹配的进行路由
            - Path=/user/{id}

