server:
  port: 8301

spring:
  application:
    name: ribbon-service
#  zipkin:
#    base-url: http://localhost:9411
    # #设置Sleuth的抽样收集概率
  #  sleuth:
  #    sampler:
  #      probability: 0.1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8001/eureka/


service-url:
  user-service: http://user-service
