server:
  port: 8401

spring:
  application:
    name: sentinel-service
  cloud:
    nacos:
      # 配置Nacos地址
      server-addr: http://localhost:8848
    sentinel:
      transport:
        # 配置Sentinel dashborad地址
        dashboard: http://localhost:8080
        port: 8719
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}-sentinel
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow

service-url:
  user-service: http://nacos-user-service


management:
  endpoints:
    web:
      exposure:
        include: '*'

# 打开sentinel对feign的支持
feign:
  sentinel:
    enabled: true